# Auto-labeling configuration for PRs
# Labels are automatically applied based on changed files

'backend':
  - backend/**/*

'frontend':
  - frontend/**/*

'documentation':
  - '**/*.md'
  - docs/**/*

'ci/cd':
  - .github/**/*

'dependencies':
  - '**/package.json'
  - '**/pnpm-lock.yaml'

'docker':
  - '**/Dockerfile*'
  - '**/docker-compose*.yml'
  - '**/.dockerignore'

'database':
  - 'backend/prisma/**/*'

'tests':
  - '**/*.spec.ts'
  - '**/*.test.ts'
  - '**/*.e2e-spec.ts'

'config':
  - '**/.env.example'
  - '**/tsconfig.json'
  - '**/.eslintrc*'
  - '**/.prettierrc*'
